/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import modelo.NRacionais;
import javax.swing.JOptionPane;

/**
 *
 * @author Henrique
 */
public class calculadora extends javax.swing.JFrame {

    /**
     * Creates new form calculadora
     */
    public calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldNumeradorN1 = new javax.swing.JTextField();
        jTextFieldDenominadorN1 = new javax.swing.JTextField();
        jTextFieldNumeradorN2 = new javax.swing.JTextField();
        jTextFieldDenominadorN2 = new javax.swing.JTextField();
        jButtonSoma = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextAreaSaida = new javax.swing.JTextField();
        jButtonSubtrai = new javax.swing.JButton();
        jButtonDivisao = new javax.swing.JButton();
        jButtonMultiplicacao = new javax.swing.JButton();
        jButtonIgual = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        jLabel1.setText("Calculadora de Números Racionais");

        jTextFieldNumeradorN1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextFieldDenominadorN1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextFieldNumeradorN2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldNumeradorN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeradorN2ActionPerformed(evt);
            }
        });

        jTextFieldDenominadorN2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButtonSoma.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jButtonSoma.setText("+");
        jButtonSoma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSoma.setInheritsPopupMenu(true);
        jButtonSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSomaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setText("NÚMERO 1");

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setText("NÚMERO 2");

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setText("RESULTADO");

        jTextAreaSaida.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jTextAreaSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAreaSaidaActionPerformed(evt);
            }
        });

        jButtonSubtrai.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jButtonSubtrai.setText("-");
        jButtonSubtrai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSubtrai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubtraiActionPerformed(evt);
            }
        });

        jButtonDivisao.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jButtonDivisao.setText("/");
        jButtonDivisao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivisaoActionPerformed(evt);
            }
        });

        jButtonMultiplicacao.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jButtonMultiplicacao.setText("*");
        jButtonMultiplicacao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplicacaoActionPerformed(evt);
            }
        });

        jButtonIgual.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jButtonIgual.setText("=");
        jButtonIgual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIgualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNumeradorN1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNumeradorN2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jTextFieldDenominadorN1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldDenominadorN2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSubtrai, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextAreaSaida)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNumeradorN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNumeradorN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldDenominadorN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldDenominadorN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonSubtrai, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jButtonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextAreaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNumeradorN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeradorN2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeradorN2ActionPerformed

    private void jButtonSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSomaActionPerformed
        // TODO add your handling code here:
        try {
            int numerador = Integer.parseInt(jTextFieldNumeradorN1.getText());
            int denominador = Integer.parseInt(jTextFieldDenominadorN1.getText());
            NRacionais numero1 = new NRacionais();
            numero1.setNracional(numerador, denominador);
            
             numerador = Integer.parseInt(jTextFieldNumeradorN2.getText());
             denominador = Integer.parseInt(jTextFieldDenominadorN2.getText());
             NRacionais numero2 = new NRacionais(numerador, denominador);
             NRacionais numero3 = numero1.adicionar(numero2);
             
             
             
            String saida = "DADOS DOS NUMEROS: \n";
            saida+= numero1.getRacional();
            saida+= "  +  " +numero2.getRacional();
            saida += "  =  " + numero3.getRacional();
            
         
            jTextAreaSaida.setText(saida);
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonSomaActionPerformed

    private void jButtonMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplicacaoActionPerformed
        try {
           int numerador = Integer.parseInt(jTextFieldNumeradorN1.getText());
            int denominador = Integer.parseInt(jTextFieldDenominadorN1.getText());
            NRacionais numero1 = new NRacionais();
            numero1.setNracional(numerador, denominador);
            
             numerador = Integer.parseInt(jTextFieldNumeradorN2.getText());
             denominador = Integer.parseInt(jTextFieldDenominadorN2.getText());
             NRacionais numero2 = new NRacionais(numerador, denominador);
             NRacionais numero3 = numero1.multiplicar(numero2);
             
             
             
            String saida = "DADOS DOS NUMEROS: \n";
            saida+= numero1.getRacional();
            saida+= "  *  " +numero2.getRacional();
            saida += "  =  " + numero3.getRacional();
            
         
            jTextAreaSaida.setText(saida); 
            
        } catch (Exception erro) {
          JOptionPane.showMessageDialog(this, erro.getMessage());  
        }

    }//GEN-LAST:event_jButtonMultiplicacaoActionPerformed

    private void jButtonDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivisaoActionPerformed
    
        try {
           int numerador = Integer.parseInt(jTextFieldNumeradorN1.getText());
            int denominador = Integer.parseInt(jTextFieldDenominadorN1.getText());
            NRacionais numero1 = new NRacionais();
            numero1.setNracional(numerador, denominador);
            
             numerador = Integer.parseInt(jTextFieldNumeradorN2.getText());
             denominador = Integer.parseInt(jTextFieldDenominadorN2.getText());
             NRacionais numero2 = new NRacionais(numerador, denominador);
             NRacionais numero3 = numero1.dividir(numero2);
             
             
             
            String saida = "DADOS DOS NUMEROS: \n";
            saida+= numero1.getRacional();
            saida+= "  /  " +numero2.getRacional();
            saida += "  =  " + numero3.getRacional();
            
         
            jTextAreaSaida.setText(saida); 
            
        } catch (Exception erro) {
          JOptionPane.showMessageDialog(this, erro.getMessage());  
        }    
        
        
        
    }//GEN-LAST:event_jButtonDivisaoActionPerformed

    private void jButtonSubtraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubtraiActionPerformed
       try {
           int numerador = Integer.parseInt(jTextFieldNumeradorN1.getText());
            int denominador = Integer.parseInt(jTextFieldDenominadorN1.getText());
            NRacionais numero1 = new NRacionais();
            numero1.setNracional(numerador, denominador);
            
             numerador = Integer.parseInt(jTextFieldNumeradorN2.getText());
             denominador = Integer.parseInt(jTextFieldDenominadorN2.getText());
             NRacionais numero2 = new NRacionais(numerador, denominador);
             NRacionais numero3 = numero1.subtrair(numero2);
             
             
             
            String saida = "DADOS DOS NUMEROS: \n";
            saida+= numero1.getRacional();
            saida+= " - " +numero2.getRacional();
            saida += " = " + numero3.getRacional();
            
         
            jTextAreaSaida.setText(saida); 
            
        } catch (Exception erro) {
          JOptionPane.showMessageDialog(this, erro.getMessage());  
        }    
    }//GEN-LAST:event_jButtonSubtraiActionPerformed

    private void jButtonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIgualActionPerformed
        // TODO add your handling code here:
        
     try {
            int numerador = Integer.parseInt(jTextFieldNumeradorN1.getText());
            int denominador= Integer.parseInt(jTextFieldDenominadorN1.getText());
            NRacionais numeroUm = new NRacionais();
            numeroUm.setNracional(numerador, denominador);
            
            int numerador1 = Integer.parseInt(jTextFieldNumeradorN2.getText());
            int denominador2 = Integer.parseInt(jTextFieldDenominadorN2.getText()); 
            NRacionais numeroDois = new NRacionais(numerador1,denominador2);
                    
              boolean numeroTres = numeroUm.eigual(numeroDois);
            
        String saida = "SAIDA DE DADOS:  ";
        saida+= numeroUm.getRacional();
        saida+= " é igual a " + numeroDois.getRacional();
        saida += "  =  "+numeroTres;
        
        
        
        jTextAreaSaida.setText(saida);
            
        } catch (Exception erro) {
          JOptionPane.showMessageDialog(this, erro.getMessage());  
        }   
    
        
    }//GEN-LAST:event_jButtonIgualActionPerformed

    private void jTextAreaSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAreaSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAreaSaidaActionPerformed

    
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDivisao;
    private javax.swing.JButton jButtonIgual;
    private javax.swing.JButton jButtonMultiplicacao;
    private javax.swing.JButton jButtonSoma;
    private javax.swing.JButton jButtonSubtrai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextAreaSaida;
    private javax.swing.JTextField jTextFieldDenominadorN1;
    private javax.swing.JTextField jTextFieldDenominadorN2;
    private javax.swing.JTextField jTextFieldNumeradorN1;
    private javax.swing.JTextField jTextFieldNumeradorN2;
    // End of variables declaration//GEN-END:variables
}
